name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: All things angular
        uses: amrashrv/angular-test-front@ref
        with:
          build_configuration: staging # The build environment for the app. please look configurations in your angular.json
          base_href: /angular-test-front/   # make sure this corresponds to https://<your_username>.github.io/<base_href>/
          deploy_branch: main # The branch the action should deploy to.
          angular_dist_build_folder: docs
